### ISSUE TITLE
Errore path matching con start locale se il path inizia per /dev

### ISSUE THREAD

**Issue by lysz210-interlogica** [sickOscar/povery-cli#1]
Lanciando il server locale il path `/devices` viene rimappato con prefisso `/dev/devices`.
Una chiamata http `curl --location 'http://localhost:3000/dev/devices'` termina con l'errore:
```
GET /dev/devices (λ: devices)
API Stage: dev
(λ: devices) RequestId: a1706173-0cea-40ad-a533-131dcee48d36  Duration: 4373.51 ms  Billed Duration: 4374 ms
Removing stage from path
API Path: ices
err Error: Route ices not found
    at getRoute (/home/lysz210/workspace/itw-eurotec/code/backend/node_modules/povery/dist/route_extractor.js:44:11)
    at execFunctionHandler (/home/lysz210/workspace/itw-eurotec/code/backend/node_modules/povery/dist/povery.js:275:62)
    at runFunction (/home/lysz210/workspace/itw-eurotec/code/backend/node_modules/povery/dist/povery.js:214:12)
    at /home/lysz210/workspace/itw-eurotec/code/backend/node_modules/povery/dist/povery.js:51:41
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MessagePort.<anonymous> (file:///home/lysz210/workspace/itw-eurotec/code/backend/node_modules/serverless-offline/src/lambda/handler-runner/worker-thread-runner/workerThreadHelper.js:24:14)
Error: Route ices not found
    at getRoute (/home/lysz210/workspace/itw-eurotec/code/backend/node_modules/povery/dist/route_extractor.js:44:11)
    at execFunctionHandler (/home/lysz210/workspace/itw-eurotec/code/backend/node_modules/povery/dist/povery.js:275:62)
    at runFunction (/home/lysz210/workspace/itw-eurotec/code/backend/node_modules/povery/dist/povery.js:214:12)
    at /home/lysz210/workspace/itw-eurotec/code/backend/node_modules/povery/dist/povery.js:51:41
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MessagePort.<anonymous> (file:///home/lysz210/workspace/itw-eurotec/code/backend/node_modules/serverless-offline/src/lambda/handler-runner/worker-thread-runner/workerThreadHelper.js:24:14)
```
L'errore e' causato da:
```
        // AWS HTTP APIs keeps stage name in path. We need to remove it to match the route
        const apiStage = event.requestContext?.stage; 
        let apiPath = event.path;
        console.log(`API Stage: ${apiStage}`);
        if (apiPath.startsWith(`/${apiStage}`)) {
            console.log(`Removing stage from path`);
            apiPath = apiPath.replace(`/${apiStage}`, '');
        }
```
nell'esecuzione `apiStage='dev'` e `apiPath='/devices'`, in questo caso entra nella if e toglie /dev da /devices lasciando ices.

**Comment by sickOscar** [comment]
Fixed with release 0.0.41

Fixed the stage name removal logic in povery.ts:
- Added a check to ensure apiStage exists before using it 
- Changed the condition to only remove the stage name if it's followed by a slash (/${apiStage}/)
- Used substring() instead of replace() for more precise control

Added tests to cover the edge cases:
- Added a test for paths that contain the stage name as part of a resource path (e.g., /dev/devices)
- Added a test for paths where the stage name is not followed by a slash (e.g., /devinfo)

Updated documentation:
- Added a section to the README explaining how stage name removal works
- Created a CHANGELOG.md file to document the fix
